name: pitch-tracking
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.3=h516909a_0
  - aom=3.3.0=h27087fc_1
  - appdirs=1.4.4=pyh9f0ad1d_0
  - apptools=5.1.0=pyh44b312d_0
  - autoreject=0.3.1=pyhd8ed1ab_0
  - blosc=1.21.1=hd32f23e_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py310h5764c6d_1004
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - c-blosc2=2.0.4=h5f21a17_1
  - ca-certificates=2021.10.8=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2021.10.8=py310hff52083_2
  - cffi=1.15.0=py310h0fdd8cc_0
  - cfitsio=4.1.0=hd9d235c_0
  - charls=2.3.4=h9c3ff4c_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - cloudpickle=2.0.0=pyhd8ed1ab_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - configobj=5.0.6=py_0
  - cryptography=36.0.2=py310h597c629_1
  - curl=7.83.0=h7bff187_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.11.2=py310h5764c6d_2
  - dask-core=2022.4.1=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - decorator=5.1.1=pyhd8ed1ab_0
  - deprecated=1.2.13=pyh6c4a22f_0
  - dipy=1.5.0=py310hde88566_1
  - double-conversion=3.2.0=h9c3ff4c_0
  - edflib-python=1.0.6=pyhd8ed1ab_0
  - eigen=3.4.0=h4bd325d_0
  - envisage=6.0.1=pyhd8ed1ab_0
  - expat=2.4.8=h27087fc_0
  - ffmpeg=4.4.1=hd7ab26d_2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.33.3=py310h5764c6d_0
  - freetype=2.10.4=h0708190_1
  - fsspec=2022.3.0=pyhd8ed1ab_0
  - future=0.18.2=py310hff52083_5
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h36c2ea0_2
  - gl2ps=1.4.2=h0708190_0
  - glew=2.1.0=h9c3ff4c_2
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - gst-plugins-base=1.20.1=hcf0ee16_1
  - gstreamer=1.20.1=hd4edc92_1
  - h5py=3.6.0=nompi_py310he751f51_100
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.12.1=nompi_h2386368_104
  - icu=69.1=h9c3ff4c_0
  - idna=3.3=pyhd8ed1ab_0
  - imagecodecs=2022.2.22=py310h31a0021_4
  - imageio=2.18.0=pyhcf75d05_0
  - imageio-ffmpeg=0.4.7=pyhd8ed1ab_0
  - importlib-metadata=4.11.3=py310hff52083_1
  - importlib_metadata=4.11.3=hd8ed1ab_1
  - importlib_resources=5.7.1=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jinja2=3.1.1=pyhd8ed1ab_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_1
  - jsoncpp=1.9.5=h4bd325d_1
  - jxrlib=1.1=h7f98852_2
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.2=py310hbf28c38_1
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libaec=1.0.6=h9c3ff4c_0
  - libavif=0.10.1=h166bdaf_0
  - libblas=3.9.0=14_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=14_linux64_openblas
  - libclang=13.0.1=default_hc23dcda_0
  - libcurl=7.83.0=h7bff187_0
  - libdeflate=1.10=h7f98852_0
  - libdrm=2.4.109=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_16
  - libgfortran-ng=11.2.0=h69a702a_16
  - libgfortran5=11.2.0=h5c6108e_16
  - libglib=2.70.2=h174f98d_4
  - libglu=9.0.0=he1b5a44_1001
  - libgomp=11.2.0=h1d223b6_16
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=14_linux64_openblas
  - libllvm13=13.0.1=hf817b99_2
  - libnetcdf=4.8.1=nompi_h329d8a1_102
  - libnghttp2=1.47.0=h727a467_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.20=pthreads_h78a6416_0
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.16=h516909a_0
  - libpng=1.6.37=h21135ba_2
  - libpq=14.2=hd57d9b9_0
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=11.2.0=he4da1e4_16
  - libtheora=1.1.1=h7f98852_1005
  - libtiff=4.3.0=h542a066_3
  - libuuid=2.32.1=h7f98852_1000
  - libva=2.14.0=h7f98852_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h885dcf4_1
  - libxslt=1.1.33=h0ef7038_3
  - libzip=1.8.0=h4de3113_1
  - libzlib=1.2.11=h166bdaf_1014
  - libzopfli=1.0.3=h9c3ff4c_0
  - locket=1.0.0=pyhd8ed1ab_0
  - loguru=0.6.0=py310hff52083_1
  - lxml=4.8.0=py310h5764c6d_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - lzo=2.10=h516909a_1000
  - markupsafe=2.1.1=py310h5764c6d_1
  - matplotlib-base=3.5.1=py310h23f4a51_0
  - mayavi=4.7.4=py310h9a68e74_1
  - mffpy=0.7.1=pyhd8ed1ab_0
  - mne-bids=0.10=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.29=haf5c9bc_0
  - mysql-libs=8.0.29=h28c427c_0
  - ncurses=6.3=h27087fc_1
  - nettle=3.6=he412f7d_0
  - networkx=2.8=pyhd8ed1ab_0
  - nibabel=3.2.2=pyhd8ed1ab_0
  - nilearn=0.9.1=pyhd8ed1ab_0
  - nomkl=1.0=h5ca1d4c_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.77=h2350873_0
  - numexpr=2.8.0=py310hf05e7a9_102
  - numpy=1.22.3=py310h4ef5377_2
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1n=h166bdaf_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.2=py310h769672d_1
  - partd=1.2.0=pyhd8ed1ab_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=9.1.0=py310he619898_2
  - pip=22.0.4=pyhd8ed1ab_0
  - pooch=1.6.0=pyhd8ed1ab_0
  - proj=9.0.0=h93bde94_1
  - psutil=5.9.0=py310h5764c6d_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - pugixml=1.11.4=h9c3ff4c_0
  - pybv=0.6.0=pyhd8ed1ab_2
  - pycparser=2.21=pyhd8ed1ab_0
  - pydicom=2.3.0=pyh6c4a22f_0
  - pyface=7.4.1=pyhd8ed1ab_0
  - pygments=2.12.0=pyhd8ed1ab_0
  - pymatreader=0.0.30=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.8=pyhd8ed1ab_0
  - pyprep=0.4.2=pyhd8ed1ab_0
  - pyqt=5.12.3=py310hff52083_8
  - pyqt-impl=5.12.3=py310h1f8e252_8
  - pyqt5-sip=4.19.18=py310h122e73d_8
  - pyqtchart=5.12=py310hfcd6d55_8
  - pyqtwebengine=5.12.1=py310hfcd6d55_8
  - pysocks=1.7.1=py310hff52083_5
  - pysurfer=0.11.0=py_0
  - pytables=3.7.0=py310hf5df6ce_0
  - python=3.10.4=h9a8a25e_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-picard=0.7=pyh8a188c0_0
  - python_abi=3.10=2_cp310
  - pytz=2022.1=pyhd8ed1ab_0
  - pyvista=0.34.0=pyhd8ed1ab_0
  - pyvistaqt=0.9.0=pyhd8ed1ab_0
  - pywavelets=1.3.0=py310hde88566_1
  - pyyaml=6.0=py310h5764c6d_4
  - qt=5.12.9=h1304e3e_6
  - qtpy=2.0.1=pyhd8ed1ab_0
  - readline=8.1=h46c0cb4_0
  - requests=2.27.1=pyhd8ed1ab_0
  - scikit-image=0.19.2=py310hb5077e9_0
  - scikit-learn=1.0.2=py310h1246948_0
  - scipy=1.8.0=py310hea5193d_1
  - scooby=0.5.12=pyhd8ed1ab_0
  - setuptools=62.1.0=py310hff52083_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.8=he1b5a44_3
  - sqlite=3.38.3=h4ff8645_0
  - statsmodels=0.13.2=py310h96516ba_0
  - svt-av1=0.9.1=h27087fc_0
  - tbb=2021.5.0=h924138e_1
  - tbb-devel=2021.5.0=h924138e_1
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tifffile=2022.4.26=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toolz=0.11.2=pyhd8ed1ab_0
  - tqdm=4.64.0=pyhd8ed1ab_0
  - traits=6.3.2=py310h5764c6d_1
  - traitsui=7.3.1=pyhd8ed1ab_0
  - typing_extensions=4.2.0=pyha770c72_1
  - tzdata=2022a=h191b570_0
  - unicodedata2=14.0.0=py310h5764c6d_1
  - urllib3=1.26.9=pyhd8ed1ab_0
  - utfcpp=3.2.1=ha770c72_0
  - vtk=9.1.0=qt_py310hf3393c1_207
  - wheel=0.37.1=pyhd8ed1ab_0
  - wrapt=1.14.0=py310h5764c6d_1
  - x264=1!161.3030=h7f98852_1
  - x265=3.5=h924138e_3
  - xlrd=2.0.1=pyhd8ed1ab_3
  - xmltodict=0.12.0=py_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - zfp=0.5.5=h9c3ff4c_8
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.11=h166bdaf_1014
  - zstd=1.5.2=ha95c52a_0
  - pip:
    - astor==0.7.1
    - bids-validator==1.9.3
    - click==8.1.3
    - docopt==0.6.2
    - formulaic==0.3.3
    - interface-meta==1.3.0
    - mne==1.1.dev0
    - num2words==0.5.10
    - pybids==0.15.1
    - sqlalchemy==1.3.24
prefix: /home/letitiayhho/.conda/envs/pitch-tracking
